name: Superheroes2
version: ${project.version}
main: me.xemor.superheroes2.Superheroes2
api-version: 1.16
authors: [Xemor_]
softdepend: [SkillsLibrary2]
description: Adds superheroes to your world - these can be customized completely and are extremely modular.
commands:
  hero:
    description: The root command of all of the commands within Superheroes2
    usage: /hero <hero> <name>
permissions:
  superheroes.hero:
    description: Allows them to use /hero
    default: op
  superheroes.reroll:
    description: Allows them to use /reroll
    default: op
  superheroes.hero.others:
    description: Allows them to use /hero on other people
    default: op
  superheroes.hero.bypasscooldown:
    description: Allows them to use /hero regardless of whether it is on cooldown or not
    default: op
  superheroes.notify:
    description: Get informed about new updates to the Superheroes2 plugin!
    default: op